version: "3"
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=app1
    ports:
      - "3000"
    networks:
      - webnet

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=app2
    ports:
      - "3000"
    networks:
      - webnet

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=app3
    ports:
      - "3000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs:/etc/nginx/certs:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - webnet

networks:
  webnet:
